name: Validate

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "0 12 * * *"

concurrency:
  cancel-in-progress: true
  group: validate-${{ github.ref }}

permissions: {}

jobs:
  preflight:
    if: ${{ github.repository == 'C3H3-AI/hacs-vision-standalone' }}
    runs-on: ubuntu-latest
    name: Preflight
    steps:
      - name: Validation preflight
        env:
          ACTOR: ${{ github.actor }}
          EVENT_NAME: ${{ github.event_name }}
          REF_NAME: ${{ github.ref_name }}
          REF: ${{ github.ref }}
          SHA: ${{ github.sha }}
        run: |
          echo "**Start:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "**Actor:** $ACTOR" >> $GITHUB_STEP_SUMMARY
          echo "**Event:** $EVENT_NAME" >> $GITHUB_STEP_SUMMARY
          echo "**Ref name:** $REF_NAME" >> $GITHUB_STEP_SUMMARY
          echo "**Ref:** $REF" >> $GITHUB_STEP_SUMMARY
          echo "**SHA:** $SHA" >> $GITHUB_STEP_SUMMARY

  validate-hassfest:
    needs:
      - "preflight"
    runs-on: ubuntu-latest
    name: With hassfest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # Test files conflict with running hassfest
      - name: Remove tests
        run: rm -rf tests

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@e3fb68ebda13d88a0d695082f471ba2c83d025fb # master

  validate-hacs:
    needs:
      - "preflight"
    runs-on: ubuntu-latest
    name: With HACS Action
    steps:
      - name: HACS validation
        uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa # main
        with:
          category: integration

  notify_on_failure:
    runs-on: ubuntu-latest
    name: Trigger Discord notification when jobs fail
    needs: ["preflight","validate-hassfest", "validate-hacs"]
    steps:
      - name: Send notification
        if: ${{ always() && contains(join(needs.*.result, ','), 'failure') && github.event_name == 'schedule' }}
        run: |
          curl \
            -H "Content-Type: application/json" \
            -d '{"username": "GitHub action failure", "content": "[Scheduled action failed!](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})"}' \
            ${{ secrets.DISCORD_WEBHOOK_ACTION_FAILURE }}
